const express = require("express");
const router = express.Router();
const { createTask, getTasks,getAllTasks,getAllTaskItems, updateTask, deleteTask } = require("../controllers/taskController");
router.route("/tasks/:boardId").get(getTasks);
router.route("/:userId/allTasks").get(getAllTasks);
router.route("/:userId/allTaskItems").get(getAllTaskItems);
router.route("/createTask/:boardId").post(createTask);
router.route("/updateTask/:taskId").put(updateTask);
router.route("/deleteTask/:taskId").delete(deleteTask);
module.exports = router;